/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTDECLARESTMT = 2;
  public int JJTASSIGNSTMT = 3;
  public int JJTWHILESTMT = 4;
  public int JJTWHILECOND = 5;
  public int JJTWHILEBLOCK = 6;
  public int JJTDOWHILESTMT = 7;
  public int JJTIFSTMT = 8;
  public int JJTIFCOND = 9;
  public int JJTIFBLOCK = 10;
  public int JJTELSEBLOCK = 11;
  public int JJTTERNARY = 12;
  public int JJTLOGEXPR = 13;
  public int JJTCOMPEXPR = 14;
  public int JJTADDEXPR = 15;
  public int JJTMULTEXPR = 16;
  public int JJTNEGEXPR = 17;
  public int JJTNOTEXPR = 18;
  public int JJTLISTEXPR = 19;
  public int JJTGENVALUE = 20;
  public int JJTIDENTIFIER = 21;
  public int JJTBOOLVALUE = 22;
  public int JJTINTVALUE = 23;
  public int JJTREALVALUE = 24;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "DeclareStmt",
    "AssignStmt",
    "WhileStmt",
    "WhileCond",
    "WhileBlock",
    "DoWhileStmt",
    "IfStmt",
    "IfCond",
    "IfBlock",
    "ElseBlock",
    "Ternary",
    "LogExpr",
    "CompExpr",
    "AddExpr",
    "MultExpr",
    "NegExpr",
    "NotExpr",
    "ListExpr",
    "GenValue",
    "Identifier",
    "BoolValue",
    "IntValue",
    "RealValue",
  };
}
/* JavaCC - OriginalChecksum=dd7b36a2a9a15ba9f106928f7b860337 (do not edit this line) */
