/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 7.0.2 */
package analyzer.ast;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTDeclareStmt node, Object data);
  public Object visit(ASTAssignStmt node, Object data);
  public Object visit(ASTWhileStmt node, Object data);
  public Object visit(ASTWhileCond node, Object data);
  public Object visit(ASTWhileBlock node, Object data);
  public Object visit(ASTDoWhileStmt node, Object data);
  public Object visit(ASTIfStmt node, Object data);
  public Object visit(ASTIfCond node, Object data);
  public Object visit(ASTIfBlock node, Object data);
  public Object visit(ASTElseBlock node, Object data);
  public Object visit(ASTTernary node, Object data);
  public Object visit(ASTLogExpr node, Object data);
  public Object visit(ASTCompExpr node, Object data);
  public Object visit(ASTAddExpr node, Object data);
  public Object visit(ASTMultExpr node, Object data);
  public Object visit(ASTNegExpr node, Object data);
  public Object visit(ASTNotExpr node, Object data);
  public Object visit(ASTListExpr node, Object data);
  public Object visit(ASTGenValue node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTBoolValue node, Object data);
  public Object visit(ASTIntValue node, Object data);
  public Object visit(ASTRealValue node, Object data);
}
/* JavaCC - OriginalChecksum=73bd41d10ad2e950243ca60cd450e71d (do not edit this line) */
