/* Generated By:JavaCC: Do not edit this line. ParserDefaultVisitor.java Version 7.0.2 */
package analyzer.ast;

public class ParserDefaultVisitor implements ParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProgram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDeclareStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssignStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhileStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhileCond node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhileBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDoWhileStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfCond node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTElseBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTernary node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLogExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCompExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAddExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMultExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNegExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNotExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTListExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGenValue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdentifier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBoolValue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntValue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRealValue node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=4c403d31382359feaeccd3fe232afc35 (do not edit this line) */
